### ISSUE TITLE
Drift physics ?

### ISSUE THREAD

**Issue by hung365dev** [SergeyMakeev/ArcadeCarPhysics#1]
Hi Sergey,

Is possible to make drift physics with your car physics ?

Thanks

**Comment by SergeyMakeev** [comment]
Should be possible. Friction model for tires computes the perfect friction force for each tire and then modulates this force by the slippery coefficient. There is handbrakes implemented in the demo you can use it by pressing 'SPACE'. Handbrakes is increases slippery coefficient for a tires to emulate a drift behaviour.
