### ISSUE TITLE
Terrain's material was not show

### ISSUE THREAD

**Issue by zoozooll** [SergeyMakeev/ArcadeCarPhysics#4]
Terrain's material was not show in my project. And the Log message in Console show like follow:

Could not create a custom UI for the shader 'ArcadeCarPhysics/Terrain'. The shader has the following: 'CustomEditor = '. Does the custom editor specified include its namespace? And does the class either derive from ShaderGUI or MaterialEditor?

**Comment by SergeyMakeev** [comment]
Should be fixed now
